# Generated by Django 6.0.3 on 2026-04-03 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kriteria', models.CharField(max_length=100)),
                ('nilai_standar', models.IntegerField()),
                ('jenis_faktor', models.CharField(choices=[('Core', 'Core'), ('Secondary', 'Secondary')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pelamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('posisi_dilamar', models.CharField(max_length=100)),
                ('pendidikan_terakhir', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_aktual', models.IntegerField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.kriteria')),
                ('pelamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.pelamar')),
            ],
        ),
    ]
