# Generated by Django 6.0.3 on 2026-05-17 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_soal', models.TextField()),
                ('pilihan_a', models.CharField(max_length=200)),
                ('pilihan_b', models.CharField(max_length=200)),
                ('pilihan_c', models.CharField(max_length=200)),
                ('pilihan_d', models.CharField(max_length=200)),
                ('pilihan_e', models.CharField(max_length=200)),
                ('kunci_jawaban', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.kriteria')),
            ],
        ),
    ]
